# Assignment 5: File Handling

This notebook contains the solutions regarding file handling problems in Python

## Problem 1:

Write a program that reads `words.txt` and prints only the words with more than 20 characters.

In [10]:
# Reading a text file:
read_file = open("resources/text_random.txt", "r")

#  Print only the words with more than 20 charcters:
for line in read_file:
    words = line.split() # Splits the line into list of words
    for word in words:
        if len(word) > 20:
            print(word)

read_file.close() # Close the file after reading

ABCDEFGHIJKLMNOPQRSTUVWXYZ
DamnThisIsAveryLongCharacterImightNOTwannaReadThis.

## Problem 2:

Write a function in python to count the number of lines from a text file `story.txt` which is not starting with an alphavet "T".

```
Example: If the file "story.txt"

A boy playing there.
There is a playground.
An aeroplane is in the sky.
The sky is pink.
Alphabets and numbers are allowed in the password.
```

In [11]:
# Read the file:
story_file = open("resources/story.txt", "r")

# Function to count the number of lines that don't start with the letter "T":
def count_lines(file):
    line_count = 0
    for line in file:
        if line[0] != "T":
            line_count += 1
    return line_count

# Count the number of lines that don't start with the letter "T" in the story file:
num_lines = count_lines(story_file)
# Close the file:
story_file.close()
print(f"The number of lines that don't start with the letter 'T' in the story file is: {num_lines}")

The number of lines that don't start with the letter 'T' in the story file is: 3

## Problem 3:

Write a program to accept two files from the user. Copy the text from first file and copy it into another file.

In [13]:
# Accepting user input file:
user_file = input("Enter the name of the file to read: ")
write_file = open(user_file, "w")

# Write some strings to the file:
write_file.write("My name is Raj Handique.\n")
write_file.write("CSD-520 Python Programming.\n")
write_file.write("This is assignment is on file handling.\n")
write_file.close()

# Read the file:
read_file = open(user_file, "r")
text = read_file.read()
read_file.close()

# Accepting user input file to copy the text:
user_file1 = input("Enter the name of file to copy: ")
# Copy the text from the user input file to a new file:
copy_file = open(user_file1, "w")
copy_file.write(text)

# Close the file after copying:
copy_file.close()

## Output of the copied file:

In [ ]:
!cat {user_file1}

My name is Raj Handique.
CSD-520 Python Programming.
This is assignment is on file handling.

## Problem 4:

Write a program to perform following operations on the given dataset. 

**Dataset:** Student Performance 

1. Load the dataset 
2. Display shape and size of the dataset 
3. Display column Names 
4. Display all the records from `Total_Marks` column 
5. Display first 5 and last 5 records 
6. Display the count of null values

In [ ]:
import pandas as pd
# 1. Load the dataset:
student_df = pd.read_csv("resources/student_performance.csv")
student_df.head()

,Student_ID,Name,Math,Science,English,History,Computer_Science,Total_Marks,Percentage,Grade
0,STU101,Aarav Sharma,88,92,79,85,95,439,87.8,A
1,STU102,Sophia Martinez,74,68,82,75,80,379,75.8,B
2,STU103,Liam Chen,95,98,89,90,99,471,94.2,A+
3,STU104,Emma Watson,62,58,70,65,72,327,65.4,C
4,STU105,Noah Patel,81,85,88,84,90,428,85.6,A

In [18]:
# 2. Display shape and size of the dataset:
print(f"Shape of the dataset: {student_df.shape}") # rows and columns 
print(f"Size of the dataset: {student_df.size}") # total number of elements

Shape of the dataset: (10, 10)
Size of the dataset: 100

In [21]:
# 3. Display the column names of the dataset:
print(f"Column names of the dataset: {student_df.columns.tolist()}")

Column names of the dataset: ['Student_ID', 'Name', 'Math', 'Science', 'English', 'History', 'Computer_Science', 'Total_Marks', 'Percentage', 'Grade']

In [27]:
# 4. Display all records from Total_Marks column:
total_marks = student_df[["Total_Marks"]]
total_marks.head(10)

   Total_Marks
0          439
1          379
2          471
3          327
4          428
5          280
6          442
7          404
8          230
9          462

In [30]:
# 5. Display first 5 and last 5 records of the dataset:
student_df.head(5) # first 5 records

,Student_ID,Name,Math,Science,English,History,Computer_Science,Total_Marks,Percentage,Grade
0,STU101,Aarav Sharma,88,92,79,85,95,439,87.8,A
1,STU102,Sophia Martinez,74,68,82,75,80,379,75.8,B
2,STU103,Liam Chen,95,98,89,90,99,471,94.2,A+
3,STU104,Emma Watson,62,58,70,65,72,327,65.4,C
4,STU105,Noah Patel,81,85,88,84,90,428,85.6,A

In [31]:
student_df.tail(5) # last 5 records

,Student_ID,Name,Math,Science,English,History,Computer_Science,Total_Marks,Percentage,Grade
5,STU106,Olivia Brown,45,52,60,58,65,280,56.0,D
6,STU107,Lucas Silva,90,87,85,88,92,442,88.4,A
7,STU108,Mia Takahashi,78,82,80,79,85,404,80.8,B+
8,STU109,Ethan Miller,35,42,50,48,55,230,46.0,F
9,STU110,Ava Johnson,92,94,91,89,96,462,92.4,A+

In [32]:
# 6. Display the count of NULL values in each column of the dataset:
null_counts = student_df.isnull().sum()
print(f"Count of NULL values in each column:\n{null_counts}")

Count of NULL values in each column:
Student_ID          0
Name                0
Math                0
Science             0
English             0
History             0
Computer_Science    0
Total_Marks         0
Percentage          0
Grade               0
dtype: int64